//
//  string.h
//  KBeaconDemo
//
//  Created by kkm on 2018/12/10.
//  Copyright © 2018 kkm. All rights reserved.
//

#ifndef string_h
#define string_h

#define STRING(a) NSLocalizedString(a, a)

#define ACTION_START_SCAN STRING(@"ACTION_START_SCAN")

#define ACTION_STOP_SCAN STRING(@"ACTION_STOP_SCAN")

#define SUCC_TITLE STRING(@"SUCC_TITLE")
#define ERR_TITLE STRING(@"ERR_TITLE")

#define ERR_BEACON_NOT_CONNECTED STRING(@"ERR_BEACON_NOT_CONNECTED")

#define DLG_OK STRING(@"DLG_OK")

#define DLG_CANCEL STRING(@"DLG_CANCEL")

#define ERR_BLE_FUNC_OFF STRING(@"ERR_BLE_FUNC_OFF")

#define ACTION_REFRESHING STRING(@"ACTION_REFRESHING")

#define PUSH_TO_RELEASE STRING(@"PUSH_TO_RELEASE")

#define BEACON_CONNECT STRING(@"BEACON_CONNECT")

#define BEACON_DISCONNECT STRING(@"BEACON_DISCONNECT")



#define DEVICE_CHECK_UPDATE STRING(@"DEVICE_CHECK_UPDATE")

#define DFU_TITLE STRING(@"DFU_TITLE")

#define DEVICE_LATEST_VERSION STRING(@"DEVICE_LATEST_VERSION")

#define DFU_CONNECT_SERVICE_FAIL STRING(@"DFU_CONNECT_SERVICE_FAIL")

#define DFU_FOUND_NEW_VERSION STRING(@"DFU_FOUND_NEW_VERSION")

#define UPDATE_CONNECTING       STRING(@"UPDATE_CONNECTING")

#define UPDATE_UPLOADING       STRING(@"UPDATE_UPLOADING")

#define UPDATE_ABORTED       STRING(@"UPDATE_ABORTED")

#define UPDATE_COMPLETE       STRING(@"UPDATE_COMPLETE")


#define UPDATE_NETWORK_FAIL STRING(@"UPDATE_NETWORK_FAIL")

#define UPDATE_STARTED STRING(@"UPDATE_STARTED")


#define DFU_CLOUDS_SERVER_ERROR STRING(@"DFU_CLOUDS_SERVER_ERROR")

#define DFU_CLOUDS_FILE_NOT_EXIST STRING(@"DFU_CLOUDS_FILE_NOT_EXIST")

#define UPDATE_NOT_FOUND_NEW_VERSION STRING(@"UPDATE_NOT_FOUND_NEW_VERSION")

#define DFU_VERSION_MAKE_SURE STRING(@"DFU_VERSION_MAKE_SURE")

#define DEVICE_FOUND_VERSION STRING(@"DEVICE_FOUND_VERSION")

#endif /* string_h */
